[Fix] `jsx-pascal-case`: support regex allow option
yannickcr/eslint-plugin-react pull request #2906
Opened 2021-01-23 07:48 UTC by bcherny

Fixes #2905.

Note: This will potentially relax existing `ignore`s:

- **Before**, `ignore`only checked exact matches
- **After**, `ignore` checks partial matches as well

I think this is fine, since it mirrors ESLint's behavior for the `camelcase` rule. If we prefer to be extra careful, I can make this a new option (eg. `ignoreRegex`).

2021-01-23 14:39 UTC, ljharb requested changes
While It's impressive you found what I believe is the only option in eslint core that accepts regex, it's very dangerous to do `new RegExp` from user-supplied values, and we won't be supporting any regex options here. It would be reasonable to support globs instead, however.

As to this rule specifically, I'd love to understand the use case a bit more - why do you need "deprecated" to be in the name on the consuming side? `import { Foo_DEPRECATED as Foo }`, for example, works fine.

2021-01-25 17:39 UTC, bcherny commented
Updated per convo in https://github.com/yannickcr/eslint-plugin-react/issues/2905

2021-01-25 18:15 UTC, ljharb approved these changes
Seems straightforward now, thanks!

2021-01-25 18:15 UTC, ljharb commented on docs/rules/jsx-pascal-case.md
> +* `ignore`: optional string-array of component names to ignore during validation (supports [minimatch](https://github.com/isaacs/minimatch)).
```suggestion
* `ignore`: optional string-array of component names to ignore during validation (supports [minimatch](https://github.com/isaacs/minimatch)-style globs).
```

2021-01-25 19:09 UTC, merged