[New] add requireDataLowercase option to no-unknown-property rule
yannickcr/eslint-plugin-react pull request #3645
Opened 2023-10-20 08:30 UTC by HermanBilous

Fixes #3643

2023-10-21 15:26 UTC, ljharb requested changes

2023-10-21 15:26 UTC, ljharb commented on lib/rules/no-unknown-property.js
> +  allowDataUpperCase: true,
let’s call this “requireDataLowercase” and default it to false.

2023-10-21 15:26 UTC, ljharb commented on tests/lib/rules/no-unknown-property.js
> +          messageId: 'unknownProp',
i think this case should have its own error message, explaining the same thing react’s does - it’s not exactly unknown, it’s valid in html.

2023-10-23 18:45 UTC, ljharb commented on tests/lib/rules/no-unknown-property.js
> +      code: '<div data-testID="bar" data-under_sCoRe="bar" />;',
can we add this same test case as invalid also, with the option set to true?

2023-10-30 17:48 UTC, ljharb commented on docs/rules/no-unknown-property.md
> +- `requireDataLowercase`: optional (default: `false`), require data-\* attributes to contain only lowercase characters. React will issue a warning when data-\* attributes contain uppercase characters
```suggestion
- `requireDataLowercase`: optional (default: `false`), require data-\* attributes to contain only lowercase characters. React will issue a warning when data-\* attributes contain uppercase characters. In order to catch such attributes, set the `requireDataLowercase` option to `true`.
```

2023-10-30 17:48 UTC, ljharb commented on lib/rules/no-unknown-property.js
> +      return (context.options[0] && context.options[0].requireDataLowercase !== 'undefined')
```suggestion
      return (context.options[0] && typeof context.options[0].requireDataLowercase !== 'undefined')
```

2023-11-09 00:00 UTC, ljharb approved these changes

2023-11-09 08:58 UTC, merged

2023-11-21 19:09 UTC, venn-eng commented
This is great, thank you! Can't wait to use it :)